matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc-4.9
      script:  
        - gcc -o test main.c 
        - ./test
